POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "name": "Carlos Henrique", 
   "email": "henriquec@gmail.com" ,
   "password": "123456"
}

###
POST http://localhost:3003/login
Content-Type: application/json

{
   "email": "henriquec@gmail.com" ,
   "password": "123456"
}
